### ISSUE TITLE
ird be egyiptomi :3

### ISSUE THREAD

**Issue by mullerrzs** [deepdev237/hulyesql#3]
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`) VALUES 
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló'),
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló');
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló'),
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló'),
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló');
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló'),
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt feladat'),
(NULL, '25', '10', '10', '4', '2024-01-08', '16', 'Kisdolgozat'),
(NULL, '25', '11', '11', '1', '2024-01-14', '3', 'Írásbeli röpdolgozat'),
(NULL, '25', '12', '12', '3', '2024-01-19', '5', 'Beszámoló'),
(NULL, '25', '1', '1', '4', '2024-01-15', '4', 'Szóbeli vizsga'),
(NULL, '25', '2', '2', '3', '2024-01-20', '2', 'Írásbeli témazáró'),
(NULL, '25', '3', '3', '5', '2024-01-10', '6', 'Gyakorlati feladat'),
(NULL, '25', '4', '4', '2', '2024-01-25', '14', 'Szorgalmi feladat'),
(NULL, '25', '5', '5', '1', '2024-01-05', '10', 'Projektmunka'),
(NULL, '25', '6', '6', '4', '2024-01-18', '1', 'Na'),
(NULL, '25', '7', '7', '3', '2024-01-22', '8', 'Házi feladat'),
(NULL, '25', '8', '8', '5', '2024-01-12', '12', 'Másik intézményből hozott értékelés'),
(NULL, '25', '9', '9', '2', '2024-01-17', '18', 'Teszt fel

**Comment by deepdev237** [comment]
Rósz

**Comment by deepdev237** [comment]
kész van geci
