### ISSUE TITLE
Rajna Torda Orak

### ISSUE THREAD

**Issue by RajnaTorda** [deepdev237/hulyesql#5]
-- Rajna Torda jegyei

-- Magyar
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '2', '1', '5', '2024-01-15', '2', 'Madách-idézetek'),
(NULL, '26', '2', '1', '1', '2024-01-15', '2', 'Madách'),
(NULL, '26', '2', '1', '3', '2023-12-07', '2', 'Arany János'),
(NULL, '26', '2', '1', '4', '2023-11-06', '2', 'Petőfi- II.'),
(NULL, '26', '2', '1', '4', '2023-10-16', '2', 'Petőfi- I.'),
(NULL, '26', '2', '1', '3', '2023-10-16', '2', 'Petőfi- I.'),
(NULL, '26', '2', '1', '5', '2023-09-25', '11', 'Órai munka');

-- Matek
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '1', '3', '5', '2023-12-18', '23', 'Logaritmus'),
(NULL, '26', '1', '3', '4', '2023-12-01', '23', 'Exponenciális függvények és egyenletek'),
(NULL, '26', '1', '3', '5', '2023-11-20', '3', 'Hatványozás, számok négyzetgyöke'),
(NULL, '26', '1', '3', '5', '2023-11-10', '2', 'Trigonometria'),
(NULL, '26', '1', '3', '5', '2023-10-20', '11', 'Koszinusztétel'),
(NULL, '26', '1', '3', '5', '2023-10-13', '4', 'Szinusztétel'),
(NULL, '26', '1', '3', '5', '2023-10-06', '3', 'Összefüggések a hegyesszögek szögfüggvények között'),
(NULL, '26', '1', '3', '4', '2023-09-25', '3', 'Hegyesszögek szögfüggvényei');

-- Történelem
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '3', '4', '4', '2024-01-12', '4', 'Az I. világháború'),
(NULL, '26', '3', '4', '4', '2023-12-20', '11', 'Feladatmegoldás'),
(NULL, '26', '3', '4', '5', '2023-11-24', '13', 'Feladatmegoldás'),
(NULL, '26', '3', '4', '1', '2023-11-20', '4', 'A szocializmus és a munkásmozgalom'),
(NULL, '26', '3', '4', '3', '2023-09-27', '4', 'Nemzetállamok születése');

-- Fizika
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '5', '6', '4', '2024-01-15', '3', 'A tükröződés törvényei, síktükör képalkotása'),
(NULL, '26', '5', '6', '3', '2024-01-15', '3', 'A tükröződés törvényei, síktükör képalkotása'),
(NULL, '26', '5', '6', '4', '2024-01-12', '10', 'Projektmunka bemutatása'),
(NULL, '26', '5', '6', '3', '2024-01-12', '10', 'Projektmunka bemutatása');

-- Angol
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '6', '2', '1', '2024-01-03', '2', 'Unit 2'),
(NULL, '26', '6', '2', '5', '2023-11-29', '4', 'Scams'),
(NULL, '26', '6', '2', '5', '2023-11-27', '4', 'Conversation'),
(NULL, '26', '6', '2', '4', '2023-11-13', '2', 'Unit 1'),
(NULL, '26', '6', '2', '5', '2023-10-20', '4', 'Eating habits'),
(NULL, '26', '6', '2', '4', '2023-10-06', '3', 'Words'),
(NULL, '26', '6', '2', '3', '2023-09-29', '3', 'Words');

-- Szakmai angol
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '10', '10', '4', '2023-12-14', '24', ''),
(NULL, '26', '10', '10', '5', '2023-11-20', '16', ''),
(NULL, '26', '10', '10', '5', '2023-10-27', '24', '');

-- Testnevelés
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '4', '5', '5', '2024-01-05', '6', 'Talajgyakorlat'),
(NULL, '26', '4', '5', '5', '2023-11-24', '14', 'Lóelem'),
(NULL, '26', '4', '5', '5', '2023-11-10', '6', 'Tempódobás'),
(NULL, '26', '4', '5', '5', '2023-10-18', '18', 'ÜCSB'),
(NULL, '26', '4', '5', '2', '2023-10-13', '6', 'Büntetődobás'),
(NULL, '26', '4', '5', '5', '2023-10-13', '6', 'Büntetődobás'),
(NULL, '26', '4', '5', '4', '2023-10-13', '6', 'Büntetődobás');

-- Adatbázis
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '7', '8', '4', '2024-01-09', '13', 'Helyettesítő karakterek'),
(NULL, '26', '7', '8', '5', '2024-01-02', '11', 'Rendezési feladatok'),
(NULL, '26', '7', '8', '5', '2023-11-28', '19', 'Update'),
(NULL, '26', '7', '8', '5', '2023-10-03', '23', 'Az adatbázis tervezés alapjai');

-- Asztali alkalmazások fejlesztése
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '11', '11', '2', '2024-01-02', '6', 'Órai munka'),
(NULL, '26', '11', '11', '5', '2023-12-19', '6', 'Adatkezelés'),
(NULL, '26', '11', '11', '5', '2023-10-03', '6', 'Órai munka');

-- IKT projektmunka II
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '12', '7', '5', '2024-01-04', '10', 'Projekt bemutatása'),
(NULL, '26', '12', '7', '5', '2023-12-07', '25', 'Felhasználói dokumentáció készítése a megadott szempontok alapján'),
(NULL, '26', '12', '7', '5', '2023-12-07', '6', 'Csoportban végzett munka Projekt elkészítése TVshop'),
(NULL, '26', '12', '7', '5', '2023-11-23', '10', 'Projekt bemutatása'),
(NULL, '26', '12', '7', '5', '2023-10-12', '11', 'Projekt készítése'),
(NULL, '26', '12', '7', '5', '2023-09-28', '10', 'Önálló projekt elkészítése bemutatása');

-- Webprogramozás
INSERT INTO `jegyek` (`id_jegyek`, `tanulo_id`, `oktato_id`, `tantargy_id`, `jegy`, `datum`, `ertekeles_modja_id`, `ertekeles_temaja`)
VALUES (NULL, '26', '9', '12', '5', '2024-01-09', '11', ''),
(NULL, '26', '9', '12', '5', '2024-01-02', '11', ''),
(NULL, '26', '9', '12', '5', '2023-12-05', '6', ''),
(NULL, '26', '9', '12', '5', '2023-10-10', '17', '');

**Comment by deepdev237** [comment]
KÉÉSSZZ
